@baseUrl = http://localhost:3000/api/
# Access protected
GET {{baseUrl}}auth/protected HTTP/1.1
# Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk3NjAxODkwMDY5OTQ1OTU4NCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzE2NjA2ODMwLCJleHAiOjE3MTY2MDc3MzB9.kuTKNocTMASG3H8Jd5ribqs-V1b8UZLmgOTgXCKsQfI eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk3NjAxODkwMDY5OTQ1OTU4NCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzE2NjA2ODMwLCJleHAiOjE3MTcyMTE2MzB9.KiOMTM2GXzD8NcyE3iTbnkwSCX0lW-34a3q65NgCf6w
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk3NjAxODkwMDY5OTQ1OTU4NCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzE2NjE5MDE2LCJleHAiOjE3MTY2MjAyMTZ9.bptSYy-yv_TWIYWjyUH7eMrYOnLJtaemm7Xzq2BcvPA