### Create a new post
POST http://localhost:3000/api/post HTTP/1.1
content-type: application/json

{
  "title": "Test title",
  "author": "Test author",
  "content": "Test content"
}

### Get all posts
GET http://localhost:3000/api/post HTTP/1.1

### Update a post
PUT http://localhost:3000/api/post/664b13e845f3601588c49a07 HTTP/1.1
content-type: application/json

{
  "title": "Updated title",
  "author": "Updated author",
  "content": "Updated content"
}

### Delete a post
DELETE http://localhost:3000/api/post/664b13e845f3601588c49a07 HTTP/1.1
Content-Type: application/json
